#include "yukit/util/entity_exists.hpp"
#include "yukit/util/get_root.hpp"
#include "yukit/util/replace_ns_qualifier.hpp"
#include "yukit/util/valid_entity_name.hpp"
#include <yukit/cmd/reference/make_template.hpp>
#include <filesystem>
#include <format>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>


namespace yukit::cmd::reference {

int make_template(std::vector<std::string> args) {
    namespace fs = std::filesystem;

    if (const auto size = args.size(); size != 0 && size != 1) {
        std::cerr << "Invalid number of arguments.\n";
        std::cerr << "For manual: yukit ref make-template <entity>\n";
        std::cerr << "For interactive: yukit make-template";
        return 1;
    }

    const fs::path root       = util::get_root();
    const fs::path yukit_root = root / "yukit";

    const bool interactive = args.empty();

    if (interactive) {
        args.resize(1);

        while (true) {
            std::cout << "Entity name: ";
            std::cin >> args[0];
            if (!util::valid_entity_name(args[0])) {
                std::cout << "\'" << args[0] << "\' is invalid for entity name.\n";
            } else if (!util::entity_exists(yukit_root, args[0])) {
                std::cout << "Entity \'" << args[0] << "\' does not exist.\n";
            } else {
                break;
            }
        }
    } else {
        if (!util::valid_entity_name(args[0])) {
            std::cerr << "\'" << args[0] << "\' is invalid for entity name.\n";
            return 1;
        } else if (!util::entity_exists(yukit_root, args[0])) {
            std::cerr << "Entity \'" << args[0] << "\' does not exist.\n";
            return 1;
        }
    }

    const std::string& entity = args[0];

    const std::string entity_name_without_yu = entity.substr(std::size("yu::") - 1);

    const fs::path mkdocs_root = root / "docs";
    const fs::path mkdocs_docs = mkdocs_root / "docs";
    const fs::path reference   = mkdocs_docs / "reference";
    const fs::path entity_ref
        = reference / std::format("{}.md", util::replace_ns_qualifier(entity_name_without_yu, "/"));

    std::ofstream ofs{entity_ref};

    ofs << "# `" << entity << "`\n"
        << '\n'
        << "{{ status_mark(\'" << entity << "\') }}\n"
        << '\n'
        << "<!-- generated by yukit -->\n";

    return 0;
}

} // namespace yukit::cmd::reference