#include <yukit/cmd/new_cmd.hpp>
#include <yukit/util/get_root.hpp>
#include <yukit/util/replace_ns_qualifier.hpp>
#include <algorithm>
#include <filesystem>
#include <format>
#include <fstream>
#include <iostream>
#include <string>
#include <string_view>
#include <vector>


namespace yukit::cmd {

int new_cmd(int argc, char* argv[]) {
    namespace fs = std::filesystem;

    if (argc < 4) {
        std::cerr << "usage: yukit new <sublib> <name> <category>\n";
        return 1;
    }

    const fs::path root = yukit::util::get_root();

    const std::string sublib   = argv[1];
    const std::string name     = argv[2];
    const std::string category = argv[3];
    const std::string status   = "planned";

    const std::string id = std::format("{}.{}", sublib, yukit::util::replace_ns_qualifier(name, "."));

    // Write yaml
    {
        const fs::path spec_dir = root / "spec" / sublib;

        if (!fs::exists(spec_dir)) {
            std::cerr << "Sublibrary \"" << sublib << "\" was not found.";
            return 1;
        }

        const std::vector<std::string> categories{
            "var",
            "var-tmpl",
            "fn",
            "fn-tmpl",
            "class",
            "class-tmpl",
            "concept",
            "alias",
            "alias-tmpl",
            "cpo",
            "fn-obj",
            "meta-fn",
        };

        if (!std::ranges::contains(categories, category)) {
            std::cerr << "Invalid category:" << category << ".\n";
            std::cerr << "Valid categories:";
            for (auto&& category : categories) { std::cerr << "\n\t" << category; }
            return 1;
        }

        const fs::path yaml_path = spec_dir / (yukit::util::replace_ns_qualifier(name, "\\") + ".yaml");

        constexpr std::string_view fmt{
            "id: {0}\n"
            "name: {1}\n"
            "category: {2}\n"
            "status: {3}\n"
        };

        const std::string yaml = std::format(fmt, id, name, category, status);

        fs::create_directories(yaml_path.parent_path());

        std::ofstream ofs{yaml_path};

        ofs << yaml;

        ofs.close();
    }

    // Write md
    {
        const fs::path md_dir = root / "docs" / "docs" / "reference" / sublib;

        if (!fs::exists(md_dir)) {
            std::cerr << "Sublibrary \"" << sublib << "\" was not found.";
            return 1;
        }

        fs::path md_path = md_dir / (name + ".md");

        if (fs::exists(md_path)) {
            std::cerr << "Markdown already exists: " << md_path << '\n';
            return 1;
        }

        const std::string normalized_name = std::format("yu::{}::{}", sublib, name);

        std::ofstream ofs(md_path);

        const std::string md = std::format(
            "# `{}`\n"
            "\n"
            "{{{{ status_mark(\'{}\') }}}}\n"
            "\n"
            "<!-- generated by yukit -->\n",
            normalized_name,
            id
        );

        ofs << md;

        ofs.close();
    }

    return 0;
}

} // namespace yukit::cmd
