name: Deploy MkDocs

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
      - "spec/**"
      - "tools/**"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Build yukit
        run: |
          cmake -S . -B build
          cmake --build build --target yukit

      - name: Generate index.json
        run: ./build/tools/yukit/yukit index

      - name: Generate .pages of Yu.Tuples
        run: ./build/tools/yukit/yukit docs pages tuples

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs
        run: |
          pip install mkdocs==1.6.1 mkdocs-material mkdocs-awesome-pages-plugin mkdocs-macros-plugin

      - name: Deploy documentation
        run: mkdocs gh-deploy --force
        working-directory: docs